Addition of users create endpoint
TimeTac/js-client-library pull request #243
Opened 2021-08-05 08:58 UTC by tjb7

2021-08-06 06:10 UTC, tjb7 commented
@tomi-timetac this is ready for review again with the additional tests and changes to the types we discussed. Please take a look when you get a chance

2021-08-06 06:15 UTC, tomi-timetac requested changes

2021-08-06 06:15 UTC, tomi-timetac commented on src/users/types.ts
> +  profile_picture: string;
I would keep the id on top

2021-08-06 06:15 UTC, tomi-timetac commented on src/users/users.test.ts
> +      console.log(JSON.stringify(err, null, 4));
console log needed?

2021-08-06 06:46 UTC, tomi-timetac submitted a review, later dismissed

2021-08-11 11:49 UTC, tomi-timetac approved these changes

2021-08-11 11:49 UTC, merged