Workaround for baseURL
TimeTac/js-client-library pull request #65
Opened 2021-01-27 12:18 UTC by benj56

As discussed we will merge the workaround for now until we can have another look at why setting that baseURL does not work.

2021-01-27 12:28 UTC, tomi-timetac requested changes

2021-01-27 12:28 UTC, tomi-timetac commented on src/index.ts
> +    // setAxiosDefaults({ baseURL: `${this.config.https ? 'https' : 'http'}://${this.config.host ?? DEFAULT_HOST}/` });
the http support needs to stay for proxying without https.

2021-01-27 13:01 UTC, tomi-timetac commented
Not happy with this change TBH, really no other way to fix this?

2021-01-27 13:17 UTC, benj56 commented
> Not happy with this change TBH, really no other way to fix this?

For the baseURL part? There is the ticket to fix the axios defaults: https://timetac.atlassian.net/browse/SB-390 but since this isn't ready in time for the desktop app release, we need to merge the workaround. 

The other part with the requestParams can be removed after https://timetac.atlassian.net/browse/PZ-3501

2021-01-28 07:14 UTC, haubitzer commented on src/tasks/index.ts
> +      Object.assign(requestParams, oldRequestParams);
This doesn't look to me like a deep copy. Because oldRequestParams and requestParams will still share the same pointer to the `criteria` object.

2021-01-28 07:22 UTC, haubitzer commented
This workaround for requestParams should not be merged in my opinion. We should try to fix it in the core and not create complexity in the CL where it is not clear way it was needed.

A possible solution for core: create a new type `plainParams` and RequestParams.from(plainParams) and the core only saves plainParams in the state.

2021-01-29 09:37 UTC, tomi-timetac approved these changes

2021-01-29 09:57 UTC, merged