Add timeTrackings/current
TimeTac/js-client-library pull request #8
Opened 2020-10-19 11:44 UTC by benj56

Using string for the user_id param while the RequestParams PR is not merged yet

2020-10-19 12:55 UTC, haubitzer requested changes

2020-10-19 12:55 UTC, haubitzer commented on src/timetrackings/index.ts
> +    const response = this._get<TimeTracking>(`${TimeTrackings.resourceName}/current${query}`);
Pls. use the options AxiosRequestConfig to add query  

This should work  this._get<TimeTracking>(`${TimeTrackings.resourceName}/current, { params: {user_id: userId} } );

2020-10-19 14:55 UTC, haubitzer approved these changes

2020-10-20 07:42 UTC, tomi-timetac approved these changes

2020-10-20 07:46 UTC, sergej-tschak approved these changes

2020-10-20 07:49 UTC, merged